INSERT 
INTO 진료내용(진료내용, 환자번호)
SELECT '고혈압', 1 FROM DUAL UNION ALL
SELECT '응급', 7 FROM DUAL UNION ALL
SELECT '수술마취', 38 FROM DUAL UNION ALL
SELECT '알레르기', 39 FROM DUAL UNION ALL
SELECT '고혈압', 98 FROM DUAL UNION ALL
SELECT '당뇨',33 FROM DUAL UNION ALL
SELECT '건강검진', 10 FROM DUAL UNION ALL
SELECT '두통', 76 FROM DUAL UNION ALL
SELECT '유방암', 45 FROM DUAL UNION ALL
SELECT '수술마취', 85 FROM DUAL UNION ALL
SELECT '비만',54 FROM DUAL UNION ALL
SELECT '수술', 85 FROM DUAL UNION ALL
SELECT '심장검사', 74 FROM DUAL UNION ALL
SELECT'수술마취', 66 FROM DUAL UNION ALL
SELECT '대장항문', 2 FROM DUAL UNION ALL
SELECT '혈액응고질환', 43 FROM DUAL UNION ALL
SELECT '유방암', 64 FROM DUAL UNION ALL
SELECT '뇌졸증', 63 FROM DUAL UNION ALL
SELECT '응급', 82 FROM DUAL UNION ALL
SELECT '자궁근종', 96 FROM DUAL UNION ALL
SELECT '알레르기', 81 FROM DUAL UNION ALL
SELECT 'MRI', 14 FROM DUAL UNION ALL
SELECT '전립선', 24 FROM DUAL UNION ALL
SELECT '유방암', 2 FROM DUAL UNION ALL
SELECT '난소종양', 50 FROM DUAL UNION ALL
SELECT '두통', 46 FROM DUAL UNION ALL
SELECT '예방접종', 76 FROM DUAL UNION ALL
SELECT '요실금', 77 FROM DUAL UNION ALL
SELECT '건강검진', 76 FROM DUAL UNION ALL
SELECT '폐결핵', 65 FROM DUAL UNION ALL
SELECT '고혈압', 49 FROM DUAL UNION ALL
SELECT '수술마취', 91 FROM DUAL UNION ALL
SELECT '천식',36 FROM DUAL UNION ALL
SELECT '흡연', 59 FROM DUAL UNION ALL
SELECT '수술마취', 93 FROM DUAL UNION ALL
SELECT '고혈압',61 FROM DUAL UNION ALL
SELECT '폐식도질환', 85 FROM DUAL UNION ALL
SELECT '당뇨', 61 FROM DUAL UNION ALL
SELECT '알레르기', 35 FROM DUAL UNION ALL
SELECT '심장초음파', 49 FROM DUAL UNION ALL
SELECT '응급', 90 FROM DUAL UNION ALL
SELECT '응급', 13 FROM DUAL UNION ALL
SELECT '내시경', 12 FROM DUAL UNION ALL
SELECT '폐렴', 80 FROM DUAL UNION ALL
SELECT '감기', 66 FROM DUAL UNION ALL
SELECT '독감', 9 FROM DUAL UNION ALL
SELECT '대장암', 36 FROM DUAL UNION ALL
SELECT '천식', 69 FROM DUAL UNION ALL
SELECT '내시경', 54 FROM DUAL UNION ALL
SELECT '독감', 98 FROM DUAL UNION ALL
SELECT '폐결핵', 99 FROM DUAL UNION ALL
SELECT '감기', 14 FROM DUAL UNION ALL
SELECT '응급',3 FROM DUAL UNION ALL
SELECT 'MRI',37 FROM DUAL UNION ALL
SELECT '폐렴', 8 FROM DUAL UNION ALL
SELECT '당뇨',53 FROM DUAL UNION ALL
SELECT '소아비만', 76 FROM DUAL UNION ALL
SELECT '갑상선질환', 52 FROM DUAL UNION ALL
SELECT '대장항문',80 FROM DUAL UNION ALL
SELECT '백내장', 34 FROM DUAL UNION ALL
SELECT '응급', 94 FROM DUAL UNION ALL
SELECT '두통', 49 FROM DUAL UNION ALL
SELECT '응급',54 FROM DUAL UNION ALL
SELECT '심장초음파', 77 FROM DUAL UNION ALL
SELECT '근골격계',72 FROM DUAL UNION ALL
SELECT '고혈압',85 FROM DUAL UNION ALL
SELECT '녹내장', 17 FROM DUAL UNION ALL
SELECT '폐결핵', 92 FROM DUAL UNION ALL
SELECT '자궁내막증', 56 FROM DUAL UNION ALL
SELECT '인공관절', 29 FROM DUAL UNION ALL
SELECT '심근경색', 66 FROM DUAL UNION ALL
SELECT '초음파',11 FROM DUAL UNION ALL
SELECT '심장판막증',81 FROM DUAL UNION ALL
SELECT '응급', 67 FROM DUAL UNION ALL
SELECT '알레르기',20 FROM DUAL UNION ALL
SELECT '초음파', 97 FROM DUAL UNION ALL
SELECT '관절경',68 FROM DUAL UNION ALL
SELECT '자궁내막증',51 FROM DUAL UNION ALL
SELECT '천식', 47 FROM DUAL UNION ALL
SELECT '피부', 79 FROM DUAL;
